packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@tailwindcss/oxide': true
  sharp: true
  unrs-resolver: true
  '@nestjs/core': true
  esbuild: true
  msgpackr-extract: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
  - '@nestjs/core'
  - esbuild
  - msgpackr-extract
